language: node_js
matrix:
  include:
    - node_js: "6.0"
sudo: required
dist: trusty
before_install:
  - sudo apt-get install libnss3-tools expect -y
before_script:

  #Setup appengine appserver?
#  - mkdir -p vendors
#  - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.40.zip -nv
#  - unzip -qd vendors google_appengine_1.9.40.zip
#  - ./vendors/google_appengine/dev_appserver.py --skip_sdk_update_check --port=8090 . &

  #Setup Lighthouse
  - npm install -g lighthouse
  - export DISPLAY=:99.0
  - export LIGHTHOUSE_CHROMIUM_PATH="$(pwd)/chrome-linux/chrome"
  - sh -e /etc/init.d/xvfb start
  - npm explore -g lighthouse -- ./lighthouse-core/scripts/download-chrome.sh
  - mv $(npm root -g)/lighthouse/chrome-linux .
  - $LIGHTHOUSE_CHROMIUM_PATH --version

  #Install dependencies
  - npm install -g bower polymer-cli http-server pwmetrics
  - bower install

  #Setup SSL db
  - mkdir -p $HOME/.pki/nssdb
  - chmod a+x create_certutil_db.sh
  - ./create_certutil_db.sh

script:

  #Build polymer project
  - polymer build

  #Run HTTPS server
  - http-server build/bundled -p 4443 -S -C ssl/server.crt -K ssl/key.pem &
  - sleep 5
  
  #Add SSL cert to trusted
  - certutil -d sql:$HOME/.pki/nssdb -A -t P -n 'localhost-cert' -i ssl/server.crt
  
  #Lighthouse
  - touch validate/log-ssl.json
  - lighthouse https://localhost:4443/ 
  - lighthouse --output=json https://localhost:4443/ --output-path=validate/log-ssl.json
  - chmod a+x validate/checklog.js
  - ./validate/checklog.js ./validate/log-ssl.json
  
  #PWMetrics
  - pwmetrics https://localhost:4443/

notifications:
  email: false
  slack:
    secure: ADt7xlh8E7bnq0PdCobSo5SRuYM56SxET+rlKZXcyGDExKCo9NSdgjAomuiJBm/ZpjnhrASO6msGjgKgmmGhmzF+H/PpgPQ/IifNIHYrJvdbflYvaj7165y7FYiLMSHAqdFFe33JKGZHpNkLKHUr3mtlIyqKhrvXpG8bhny5ObL0Aoo21OcWsNbsDWwGRu6yWVdX5sehbvskOWPALTXmL0d56LtujlprnmvI4Ae7QfDcAlVkTt+VliRtLtcH+f5VtSiHAnlrlhy1Idpjmq5AmDeEau9kovp2sxQ+RUmAw8P9QwkVclpEv5997t6zFzVJV+IraTgbFagJNEMWK+NFkZRsEHgk0P8yyNVadzGZtE8czfb/tUg5tuRUhJEDxmHJM83Pqr++QCaSR5B1Wk5fY+IhJ5Hlwzc+CurpNreiwOP+DffaKosCh9cmuMP9PJxKfmpvTnlzp9zGbp+BupJYakGRNMSZQD9UvRm350367gtOTm+d+rMfBWO4QCD1kcZLAwMd7OhEyVYNbma7euURzOjKO2iNCmdUh+hZvlVdItkjdP3Qa2PgAO6id3sZJkq45tlgEDrlgL5mr+LreHy54WMMCXohhp/NatFC7HO8bpX1WNrVRoz82c9FAklhsk1qoYL20KkW+CQIrPclagALD3NNog1K8D4Kajq/IvwvPdM=
